name: Test

on:
  push:
    branches: [ 'main', 'test-test' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        neovim: [ nightly, stable ]

    name: Tests (neovim@${{ matrix.neovim }})
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: josa42/gha-plenary-busted@main
        with:
          neovim-version: "${{ matrix.neovim }}"
          specs: spec
